// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6LyU-V7O13uIPZ12KwjAxa51t8fxAPms',
    appId: '1:1097880889381:web:ff29b0c30bb637c07bf7cc',
    messagingSenderId: '1097880889381',
    projectId: 'tic-tac-toe-app-803a0',
    authDomain: 'tic-tac-toe-app-803a0.firebaseapp.com',
    storageBucket: 'tic-tac-toe-app-803a0.appspot.com',
    measurementId: 'G-MSJZK71TK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8yrf1bvM0VOyrwRyKFRTM9DWQX1vxHk8',
    appId: '1:1097880889381:android:5c17a0e9792a7b847bf7cc',
    messagingSenderId: '1097880889381',
    projectId: 'tic-tac-toe-app-803a0',
    storageBucket: 'tic-tac-toe-app-803a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbn5iurrugLTFNjx6j2wvZ2zBlzaYz6k',
    appId: '1:1097880889381:ios:d39a23415cef39797bf7cc',
    messagingSenderId: '1097880889381',
    projectId: 'tic-tac-toe-app-803a0',
    storageBucket: 'tic-tac-toe-app-803a0.appspot.com',
    iosBundleId: 'com.mizoijin.tictactoe.ticTacToeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbn5iurrugLTFNjx6j2wvZ2zBlzaYz6k',
    appId: '1:1097880889381:ios:d39a23415cef39797bf7cc',
    messagingSenderId: '1097880889381',
    projectId: 'tic-tac-toe-app-803a0',
    storageBucket: 'tic-tac-toe-app-803a0.appspot.com',
    iosBundleId: 'com.mizoijin.tictactoe.ticTacToeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6LyU-V7O13uIPZ12KwjAxa51t8fxAPms',
    appId: '1:1097880889381:web:87a5e2bd3045c7b07bf7cc',
    messagingSenderId: '1097880889381',
    projectId: 'tic-tac-toe-app-803a0',
    authDomain: 'tic-tac-toe-app-803a0.firebaseapp.com',
    storageBucket: 'tic-tac-toe-app-803a0.appspot.com',
    measurementId: 'G-33WJCJZ8YE',
  );
}
